### ISSUE TITLE
Feedback - Ahana

### ISSUE THREAD

**Issue by ahananamburi** [w201rdada/portfolio-TomHunter1#3]
This is a great idea that weaves the concept of SMART goals with the principles of GRIT and Self Efficacy inprovement. There seem to be several apps offering tracking of SMART goals, but this is a great development on that.

It is unclear to me as to what the solution will achieve - will it provide advice based on the personality type? (As described in the conclusion) Will it give the user the probability of success and failure for the given advice? ( as described in the intro). This message could be clearer creating a consistent story from the introduction to the conclusion.

Can you also describe the dataset further? Is the solution being built on a dataset that constitutes the personality types of people, their goals and a record of their success/failure? If yes, it would help to describe that and the source of the data? Is there need to build such a dataset? 

Additionally, it might help to evaluate different personality tests and present the reason for a choice of a specific test.  Depending on the dataset, could you present a choice to the user to take one of multiple tests?

**Comment by TomHunter1** [comment]
Great feedback and food to think about
